services:
  ravendb:
    image: ravendb/ravendb:latest
    container_name: ravendb
    ports:
      - "8080:8080"   # Web UI
      - "38888:38888" # TCP (optional)
    environment:
      - RAVEN_Setup_Mode=None
      - RAVEN_License_Eula_Accepted=true
      - RAVEN_Security_UnsecuredAccessAllowed=PrivateNetwork
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/admin/stats"]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 60s
    #volumes:
    #  - ravendb_data:/opt/RavenDB/Server/RavenData
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
  redisinsight: ##UI para ver la informacion de redis, no es necesario pero es util
    image: redis/redisinsight:latest
    container_name: redisinsight
    ports:
      - "32771:5540" 
  neo4j:
    image: neo4j:latest
    container_name: neo4j
    ports:
      - "7474:7474" # HTTP
      - "7687:7687" # Bolt
    environment:
      - NEO4J_AUTH=none
  api:
    build: .
    container_name: api
    depends_on:
      ravendb:
        condition: service_healthy
    environment:
      - PORT=3000
      - RAVENDB_URL=http://ravendb:8080
      - RAVENDB_DB=test
    ports:
      - "3000:3000"

#volumes:
#  ravendb_data: # TODO